server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://192.168.0.104:9411
  sleuth:
    sampler:
      #采样率值介于0到1之间，1则表示全部采集
      probability: 1


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
