server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#feign超时控制
ribbon:
  ReadTimeOut: 5000
  ConnectTimeOut: 5000


logging:
  level:
    #feign日志以什么级别监控哪个接口
    cn.lj.springcloud.service.PaymentFeignService: debug
